services:
  - type: cron
    name: rsi-streak-phemex
    schedule: "0 */4 * * *"  # alle 4 Stunden
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python rsi_phemex_bot.py"
