services:
  - type: cron
    name: tradingview-rsi-streak
    schedule: "0 */4 * * *"  # Alle 4 Stunden
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 start.py rsi"
