services:
  - type: cron
    name: rsi-streak-phemex
    schedule: "0 */4 * * *"
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start.py rsi"
